# Generated by Django 4.2.28 on 2026-05-15 12:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('total_days', models.IntegerField(default=1)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('times', models.JSONField(default=list)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='core.person')),
            ],
        ),
    ]
